development:
  braintree_dropin_token: = <%= ENV['BRAINTREE_DROPIN_TOKEN'] %>
  braintree_env: = <%= ENV['BRAINTREE_ENV'] %>
  braintree_merchant_id: = <%= ENV['BRAINTREE_MERCHANT_ID'] %>
  braintree_public_key: = <%= ENV['BRAINTREE_PUBLIC_KEY'] %>
  braintree_private_key: = <%= ENV['BRAINTREE_PRIVATE_KEY'] %>
production:
  braintree_dropin_token: = <%= ENV['BRAINTREE_DROPIN_TOKEN'] %>
  braintree_env: = <%= ENV['BRAINTREE_ENV'] %>
  braintree_merchant_id: = <%= ENV['BRAINTREE_MERCHANT_ID'] %>
  braintree_public_key: = <%= ENV['BRAINTREE_PUBLIC_KEY'] %>
  braintree_private_key: = <%= ENV['BRAINTREE_PRIVATE_KEY'] %>
test:
  braintree_dropin_token: = <%= ENV['BRAINTREE_DROPIN_TOKEN'] %>
  braintree_env: = <%= ENV['BRAINTREE_ENV'] %>
  braintree_merchant_id: = <%= ENV['BRAINTREE_MERCHANT_ID'] %>
  braintree_public_key: = <%= ENV['BRAINTREE_PUBLIC_KEY'] %>
  braintree_private_key: = <%= ENV['BRAINTREE_PRIVATE_KEY'] %>
