development:
  stripe_public_key: = <%= ENV['STRIPE_PUBLIC_KEY'] %>
  stripe_private_key: = <%= ENV['STRIPE_PRIVATE_KEY'] %>
production:
  stripe_public_key: = <%= ENV['STRIPE_PUBLIC_KEY'] %>
  stripe_private_key: = <%= ENV['STRIPE_PRIVATE_KEY'] %>
test:
  stripe_public_key: = <%= ENV['STRIPE_PUBLIC_KEY'] %>
  stripe_private_key: = <%= ENV['STRIPE_PRIVATE_KEY'] %>
